[pytest]

addopts = -s -v

python_files = test*.py
python_functions = test_*
python_classes = Test*

markers =
    product_positive: позитивные тесты объекта Product
    product_negative: негативные тесты объекта Product
    category_positive: позитивные тесты объекта Category
    category_negative: негативные тесты объекта Category
    smartphone_positive: позитивные тесты объекта Smartphone
    smartphone_negative: негативные тесты объекта Smartphone
    lawngrass_positive: позитивные тесты объекта LawnGrass
    lawngrass_negative: негативные тесты объекта LawnGrass
