[pytest]

addopts = -s -v

python_files = test*.py
python_functions = test_*
python_classes = Test*

markers =
    product_positive: позитивные тесты объекта Product
    product_negative: негативные тесты объекта Product
    category_positive: позитивные тесты объекта Category
    category_negative: негативные тесты объекта Category
